// export const utilPaths = {
//   EMBEDDED_ICON_LIGHT_PATH: process.env.UTILS_EMBEDDED_ICON_LIGHT_PATH,
//   EMBEDDED_ICON_DARK_PATH: process.env.UTILS_EMBEDDED_ICON_DARK_PATH,
//   WEB_ICON_LIGHT_PATH: process.env.UTILS_WEB_ICON_LIGHT_PATH,
//   WEB_ICON_DARK_PATH: process.env.UTILS_WEB_ICON_DARK_PATH,
//   CLOUD_ICON_LIGHT_PATH: process.env.UTILS_CLOUD_ICON_LIGHT_PATH,
//   CLOUD_ICON_DARK_PATH: process.env.UTILS_CLOUD_ICON_DARK_PATH,
// };
