import Head from "next/head";
import { useState } from "react";
//COMPONENTS_BEGIN
import  Navbar  from "./components/Navbar";
import  Introduction from "./components/Introduction";
import  Skills  from "./components/Skills";
import  Portfolio  from "./components/Portfolio";
//COMPONENTS_END
export default function Resume() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Zoltán Berkula Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <Navbar arg={darkMode} cb={setDarkMode} />
        <Introduction />
        <Skills />
        <Portfolio />
      </main>
    </div>
  );
}
